import '../styles/globals.css'
import { pixelFont } from '../utils/font'
import DialogProvider from './context/DialogContext'
import StyledComponentsRegistry from './views/common/registry'
import Header from './views/header/header'
import ModalContextProvider from './context/ModalContext'
import '../styles/nprogress.css'
import NProgress from './views/common/NProgress'

export const metadata = {
  title: 'Create Next App',

  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={pixelFont.className}>
      <body>
        {/*<NProgress />*/}
        <StyledComponentsRegistry>
          <DialogProvider>
            <ModalContextProvider>
              <Header />
              {children}
            </ModalContextProvider>
          </DialogProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
